# reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"
    - "plugin:ec0lint-comments/recommended"

settings:
    staticResources:
        images:
            something: "something"

rules:
    no-extra-semi: "error"
