reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"

rules:
    no-whitespace-before-property: "error"
    object-curly-newline: ["error", { "consistent": true, "multiline": true }]
    object-curly-spacing: ["error", "always"]
    object-property-newline: ["error", { "allowAllPropertiesOnSameLine": true }]
    object-shorthand: "error"
    one-var-declaration-per-line: "error"
    operator-assignment: "error"
    operator-linebreak: "error"
    prefer-arrow-callback: "error"
    prefer-const: "error"
    prefer-exponentiation-operator: "error"
    prefer-numeric-literals: "error"
    prefer-promise-reject-errors: "error"
    prefer-regex-literals: "error"
    prefer-rest-params: "error"
    prefer-spread: "error"
    prefer-template: "error"
    quotes: ["error", "double", {avoidEscape: true}]
    quote-props: ["error", "as-needed"]
    radix: "error"
    require-unicode-regexp: "error"
    rest-spread-spacing: "error"
    semi: "error"
    semi-spacing: ["error", {before: false, after: true}]
    semi-style: "error"
    space-before-blocks: "error"
    space-in-parens: "error"
    space-infix-ops: "error"
    space-unary-ops: ["error", {words: true, nonwords: false}]
    spaced-comment: ["error", "always", { exceptions: ["-"]}]
    strict: ["error", "global"]
    switch-colon-spacing: "error"
    symbol-description: "error"
    template-curly-spacing: ["error", "never"]
    template-tag-spacing: "error"
    unicode-bom: "error"
    wrap-iife: "error"
    yield-star-spacing: "error"
    yoda: ["error", "never", { exceptRange: true }]
