# reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"
    - "plugin:node/recommended"
    - "plugin:jsdoc/recommended"
    - "plugin:ec0lint-comments/recommended"

settings:
    staticResources:
        images:
            something: "something"

rules:
    axios-calls: "error"
    font-format: "error"
