reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"

rules:
    unicode-bom: "error"
    wrap-iife: "error"
    yield-star-spacing: "error"
    yoda: ["error", "never", { exceptRange: true }]
