reportUnusedDisableDirectives: true
extends:
    - "ec0lint:recommended"

rules:
   lighter-http: "error"
   avoid-lodash: "error"
   no-ajax-events: "error"
   no-date-fns: "error"
   no-moment-js: "error"

